version: 1
update_configs:
  #  TODO: Modules will be enabled slowly as baseline stabilizes and framework matures.
  - package_manager: "java:maven"
    directory: ""
    update_schedule: "daily"
    target_branch: "master"
    default_labels:
      - "dependencies"